version: '3.4'

volumes:
  macnut-data: 

services:
  macnut.api:
    image: ${DOCKER_REGISTRY-}macnutapi
    build:
      context: .
      dockerfile: MacNut.Api/Dockerfile

  macnut.ui:
    image: ${DOCKER_REGISTRY-}macnutui
    build:
      context: .
      dockerfile: MacNut.UI/Dockerfile
  
  macnut.db:
    container_name: MacNut.Db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: macnut
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: ./data
    ports:
      - 5432:5432
    volumes:
      - macnut-data:/var/lib/postgresql/data


